apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-app
spec:
  selector:
    matchLabels:
      app: backend-app
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: backend-app
    spec:
      containers:
        - name: backend-app
          image: ${REPOSITORY_TAG}
          imagePullPolicy: IfNotPresent
---
apiVersion: v1
kind: Service
metadata:
  name: backend-app-service
spec:
  selector:
    app: backend-app
  ports:
    - name: http
      port: 8080
  type: ClusterIP