pipeline {
    agent any
    
    environment {
        DOCKERHUB_PASSWORD="D3l1M@qa1/"
		DOCKERHUB_USERNAME="umidrahimov"
        APP_NAME = "phonebook-backend"
        REPOSITORY_TAG="${DOCKERHUB_USERNAME}/${APP_NAME}:${BUILD_ID}"
	}
    
    stages {
        stage('Build docker image') {
            steps {
                sh 'docker build --file Phonebook_Backend/Dockerfile -t ${REPOSITORY_TAG} Phonebook_Backend/'
            }
        }
        stage('Login to DockerHub') {
			steps {
				sh 'docker login -u $DOCKERHUB_USERNAME -p $DOCKERHUB_PASSWORD'
			}
		}
        stage('Push docker image to registry') {
            steps {
                sh 'docker push ${REPOSITORY_TAG}'
            }
        }
         stage('Deploy to Cluster') {
          steps {
                sh 'envsubst < ${WORKSPACE}/Phonebook_Backend/deployment.yaml | kubectl apply -f -'
            }
        }
    }
}